### PR TITLE
Allow more attributes

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
E.g. for classes, now up to 20 attributes are allowed.

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@mconcas of course we don't have to go crazy with the number of instance attributes, but I think we should allow more than 10.
Another option would be to disable this check altogether for `pylint`.

As you can see, there is https://github.com/AliceO2Group/o2tuner/pull/61 where it complains due to 11 instance attributes.
However, I think it should be okay.

Do you have a strong opinion on this?

**Comment by benedikt-voelkel** [comment]
In a next step, I will tackle these `pytest` issues.
Once done, we can discuss https://github.com/AliceO2Group/o2tuner/pull/61

**Comment by benedikt-voelkel** [comment]
@mconcas I moved now to the correct `numpy.nan` instead of previously using the alias `numpy.NAN`. Don't know why I did that in the first place...

**Review by mconcas — APPROVED** [review]

**Comment by mconcas** [comment]
Hi @benedikt-voelkel , no objections with the number of args, let's unblock #61

**Pull request merged**
